#!/bin/bash
# Load functions and variables
jbt=$(cat /usr/bin/.jbtype)
jbtype=$(echo $jbt)

export NEWT_COLORS='root=,black
border=white,black
title=white,black
roottext=red,black
window=red,black
textbox=white,black
button=black,green
compactbutton=white,black
listbox=white,black
actlistbox=black,white
actsellistbox=black,green
checkbox=green,black
actcheckbox=black,green
'

if [ "$jbtype" = "Rootless" ]; then
  OPTIONS=$(gum choose --cursor-prefix "[ ] " --selected-prefix "[✓] " --no-limit --item.foreground 222 --selected="Debug Log (5)" < options.md | cut -d ' ' -f3 | tr -d '()')
  if [ $? = 0 ]; then
      output=""
      for OPTION in $OPTIONS; do
          case $OPTION in
              "1") output1="-V";;
              "2") output2="-s";;
              "3") output3="--force-revert";;
              "4") output4="-e 'serial=3'";;
              "5") output5="-v";;
          esac
      done
      echo "$output1 $output2 $output3 $output4 $output5" > /usr/bin/.args
      /usr/bin/palera1n_menu
  else
      echo "Cancelled"
  fi
elif [ "$jbtype" = "Rootful" ]; then
  OPTIONS="$(whiptail --separate-output --nocancel --ok-button "Select" --title "palera1n options" --checklist \
  "Press spacebar to select option, and enter to complete" 15 54 5 \
  "1" "Create FakeFS" OFF \
  "2" "Create BindFS 'experimental'" OFF \
  "3" "Verbose" OFF \
  "4" "Safe Mode" OFF \
  "5" "Restore RootFS" OFF \
  "6" "Serial" OFF \
  "7" "Debug" ON 3>&1 1>&2 2>&3)"
  if [ $? = 0 ]; then
      output=""
      for OPTION in $OPTIONS; do
          case $OPTION in
              "1") output1="-c";;
              "2") output2="-B";;
              "3") output3="-V";;
              "4") output4="-s";;
              "5") output5="--force-revert";;
              "6") output6="-e 'serial=3'";;
              "7") output7="-v";;
          esac
      done
      echo "$output1 $output2 $output3 $output4 $output5 $output6 $output7" > /usr/bin/.args
      /usr/bin/palera1n_menu
  else
      echo "Cancelled"
  fi
fi
