#!/bin/bash
# Load functions and variables
. /usr/bin/common
export LC_CTYPE="en_US.UTF-8"
arg=$(cat /usr/bin/.args)
args=$(echo $arg)
jbt=$(cat /usr/bin/.jbtype)
jbtype=$(echo $jbt)
color=$((($RANDOM%6)+1))
border=$(($color+8))

if [ "$jbtype" = "Rootless" ]; then
while true; do
  CHOICE=$(gum table -f palen1x_menu.csv -w 6,7 --height 15 --header.foreground $color --cell.border rounded --cell.foreground $border | cut -d ',' -f 1)
  gum format -t markdown "# Jailbreak Type: $jbtype"
  gum format -t markdown "## Arguments: $args"
  case "$CHOICE" in
    1)
      clear
      gum style --foreground 3 --border-foreground 11 --border rounded --align normal --margin "1 2" --padding "2 4" '== INFORMATION ==' 'If you encounter lockdownd errors make sure to unlock your device and replug.' 'arm64e is not supported!' '===== DEBUG =====' 'Chosen Jailbreak Type:'$jbtype'' 'Chosen Flags: '$args''
      /usr/bin/palera1n $args
      sleep 2
      gum style --foreground 3 --border-foreground 11 --border rounded --align double --margin "1 2" --padding "2 4" '===== DEBUG =====' 'Chosen Jailbreak Type: '$jbtype'' 'Chosen Flags: '$args''
      enter_to_quit
      /usr/bin/palera1n_menu
      ;;
    2)
      clear
      /usr/bin/palera1n_options
      ;;
    3)
      clear
      /usr/bin/palera1n_switch
      ;;
    4)
      clear
      /usr/bin/palen1x_menu
      ;;
  esac
done
elif [ $jbtype = "Rootful" ]; then
while true; do
  CHOICE=$(gum table -f palen1x_menu.csv -w 6,7 --height 15 --header.foreground $color --cell.border thick --cell.foreground $border | cut -d ',' -f 1)
  gum format -t markdown "# Jailbreak Type: $jbtype"
  gum format -t markdown "## Arguments: $args"
  case $CHOICE in
    1)
      clear
      gum style --foreground 3 --border-foreground 11 --border rounded --align normal --margin "1 2" --padding "2 4" '== INFORMATION ==' 'If you encounter lockdownd errors make sure to unlock your device and replug.' 'arm64e is not supported!' '===== DEBUG =====' 'Chosen Jailbreak Type:'$jbtype'' 'Chosen Flags: '$args''
      /usr/bin/palera1n -f $args
      sleep 2
      gum style --foreground 3 --border-foreground 11 --border rounded --align double --margin "1 2" --padding "2 4" '===== DEBUG =====' 'Chosen Jailbreak Type: '$jbtype'' 'Chosen Flags: '$args''
      enter_to_quit
      /usr/bin/palera1n_menu
      ;;
    2)
      clear
      /usr/bin/palera1n_options
      ;;
    3)
      clear
      /usr/bin/palera1n_switch
      ;;
    4)
      clear
      /usr/bin/palen1x_menu
      ;;
  esac
done
fi
