#!/bin/bash
# Load functions and variables
. /usr/bin/common
PALEN1X_VERSION="1.0.6"
export LC_CTYPE="en_US.UTF-8"
color=$((($RANDOM%6)+1))
border=$(($color+8))
while true; do
  gum format -t markdown "## palen1x $PALEN1X_VERSION"
  CHOICE=$(gum table -f palen1x_menu.csv -w 6,9 --height 15 --header.foreground $color --cell.border rounded --cell.foreground $border | cut -d ',' -f 1)
  case "$CHOICE" in
    1)
      clear
      /usr/bin/palera1n_menu
      ;;
    2)
      clear
      /usr/bin/ssh_into_ios
      ;;
    3)
      clear
      /bin/bash -i && exit
      ;;
    4)
      palen1x_logo
      sleep 2
      /sbin/poweroff
      ;;
    5)
      palen1x_logo
      sleep 2
      /sbin/reboot
      ;;
  esac
done
