#!/bin/bash
jbt=$(cat /usr/bin/.jbtype)
jbtype=$(echo $jbt)

gum format -t markdown "## Only use this if you know what you are doing. This will also wipe your chosen args."
jbtype=$(gum choose "Rootful" "Rootless")
case $jbtype in
  Rootful)
    echo "Rootful selected"
    echo "Rootful" > /usr/bin/.jbtype
    rm -r /usr/bin/.args
    /usr/bin/palera1n_menu
    ;;
  Rootless)
    echo "Rootless selected"
    echo "Rootless" > /usr/bin/.jbtype
    rm -r /usr/bin/.args
    /usr/bin/palera1n_menu
    ;;
esac
