#!/bin/bash
# Load functions and variables
jbt=$(cat /usr/bin/.jbtype)
jbtype=$(echo $jbt)

if [ $jbtype = "Rootless" ]; then
  OPTIONS=$(gum choose --cursor-prefix "[ ] " --selected-prefix "[✓] " --no-limit --item.foreground 222 --selected="7 Debug" < options.md | cut -d ' ' -f1)
  if [ $? = 0 ]; then
      output=""
      for OPTION in $OPTIONS; do
          case $OPTION in
              "1") output1="-V";;
              "2") output2="-s";;
              "3") output3="--force-revert";;
              "4") output4="-e 'serial=3'";;
              "5") output5="-v";;
          esac
      done
      echo $output1 $output2 $output3 $output4 $output5 > /usr/bin/.args
      /usr/bin/palera1n_menu
  else
      echo "Cancelled"
  fi
elif [ $jbtype = "Rootful" ]; then
  OPTIONS=$(gum choose --cursor-prefix "[ ] " --selected-prefix "[✓] " --no-limit --item.foreground 222 --selected="7 Debug" < more_options.md | cut -d ' ' -f1)
  if [ $? = 0 ]; then
      output=""
      for OPTION in $OPTIONS; do
          case $OPTION in
              "1") output1="-c";;
              "2") output2="-B";;
              "3") output3="-V";;
              "4") output4="-s";;
              "5") output5="--force-revert";;
              "6") output6="-e 'serial=3'";;
              "7") output7="-v";;
          esac
      done
      echo $output1 $output2 $output3 $output4 $output5 $output6 $output7 > /usr/bin/.args
      /usr/bin/palera1n_menu
  else
      echo "Cancelled"
  fi
fi
